CC := m68k-amigaos-gcc

# Which frontend to build: gadtools (default) or mui.
#   make              -> AmiDrop           (GadTools)
#   make GUI=mui      -> AmiDrop_MUI
GUI ?= gadtools

# Additional MUI SDK headers.  The cross-compiler's own proto/inline headers
# must take precedence because they match the installed GCC; this directory is
# used only as a fallback for headers not supplied by the toolchain.
MUI_INCLUDE ?= /home/andiw/dev/amiga/sdk/MUI/Developer/C/Include

# -MMD -MP make gcc emit a .d file per object listing the headers it read, so
# a header edit actually rebuilds. Without it, changing include/gui.h - the ABI
# contract between main.o and the frontend .o - rebuilt nothing at all.
BASE_CFLAGS := -m68000 -Os -Wall -Wextra -Wshadow -Wpointer-arith -Wframe-larger-than=1024 -DNO_INLINE_STDARG -Iinclude -MMD -MP
CFLAGS := $(BASE_CFLAGS)
LDFLAGS := -noixemul

COMMON_SOURCES := src/main.c src/server.c src/prefs.c src/util.c src/webpage.c src/qrcode.c

ifeq ($(GUI),gadtools)
  TARGET := AmiDrop
  GUI_SOURCES := src/gui.c
  GUI_LIBS :=
else ifeq ($(GUI),mui)
  TARGET := AmiDrop_MUI
  # clipboard.c is built only here for now: it is the only frontend with a
  # Copy button.  This keeps the clipboard.device code out of the GadTools
  # build; the IFF builder and URL composer live in util.c and are shared.
  GUI_SOURCES := src/gui_mui.c src/clipboard.c
  # MUI_NewObject(), MUI_MakeObject() and MUI_Request() are the varargs
  # convenience entry points supplied by libmui.a in this toolchain.  The
  # lower-level BOOPSI helpers used by the MUI macros come from amiga.lib.
  # Keep libmui before amiga.lib so static-library dependencies resolve in
  # the normal left-to-right linker order.
  GUI_LIBS := -lmui -lamiga
  # The MUI build ships under its own name, so it needs its own version cookie.
  CFLAGS += -DAMIDROP_GUI_MUI
else
  $(error Unknown GUI "$(GUI)" - use gadtools or mui)
endif

SOURCES := $(COMMON_SOURCES) $(GUI_SOURCES)

# Objects live per frontend.  Sharing one src/*.o between frontends would
# silently reuse files compiled with different flags - which is how a MUI
# binary once ended up carrying the GadTools version cookie.
OBJDIR := obj/$(GUI)
OBJECTS := $(patsubst src/%.c,$(OBJDIR)/%.o,$(SOURCES))

# The user's classic MUI 3.8 SDK contains GCC-2.x inline assembler that does
# not parse with the current m68k-amigaos-gcc.  Do NOT put that SDK first in
# the include search path.  The compiler/toolchain MUI proto+inline headers are
# ABI-matched to this GCC and must win; -idirafter keeps the external SDK as a
# fallback only.
#
# NO_INLINE_STDARG must be removed for this one translation unit because the
# MUI object construction macros need the varargs MUI_NewObject/MUI_MakeObject
# wrappers.  -fno-inline is intentional: with older m68k GCC/MUI inline
# wrappers, inlining these varargs helpers can lose anonymous arguments.
# MUIC_* are char* while the prototypes use CONST_STRPTR, hence the local
# pointer-sign suppression for the MUI frontend only.
$(OBJDIR)/gui_mui.o: CFLAGS := $(filter-out -DNO_INLINE_STDARG,$(CFLAGS)) -Wno-pointer-sign -fno-inline -idirafter $(MUI_INCLUDE)

HOST_TEST_UTIL := tests/test_util
HOST_TEST_QR := tests/test_qr

.PHONY: all clean host-test

all: $(TARGET)

# These two must stand AFTER the first real rule: a rule placed above "all"
# would become make's default goal, and "make GUI=x" would then build one
# object file instead of the program.
#
# A flag change must rebuild, not just a source change.
$(OBJECTS): Makefile

# Per-object header dependencies generated by -MMD -MP.
-include $(OBJECTS:.o=.d)

$(TARGET): $(OBJECTS)
	$(CC) -o $@ $(OBJECTS) $(LDFLAGS) $(GUI_LIBS)

$(OBJDIR):
	mkdir -p $(OBJDIR)

$(OBJDIR)/%.o: src/%.c | $(OBJDIR)
	$(CC) $(CFLAGS) -c -o $@ $< $(LDFLAGS)

host-test: $(HOST_TEST_UTIL) $(HOST_TEST_QR)
	./$(HOST_TEST_UTIL)
	./$(HOST_TEST_QR)

$(HOST_TEST_UTIL): tests/test_util.c src/util.c include/util.h include/amidrop.h
	gcc -std=c99 -O2 -Wall -Wextra -Iinclude -o $@ tests/test_util.c src/util.c

$(HOST_TEST_QR): tests/test_qr.c src/qrcode.c include/qrcode.h include/amidrop.h
	gcc -std=c99 -O2 -Wall -Wextra -Iinclude -o $@ tests/test_qr.c src/qrcode.c

clean:
	rm -rf obj
	rm -f AmiDrop AmiDrop_MUI $(HOST_TEST_UTIL) $(HOST_TEST_QR)
