CC := m68k-amigaos-gcc

# Which frontend to build: gadtools (default), reaction or mui.
#   make              -> AmiDrop           (GadTools)
#   make GUI=mui      -> AmiDrop_MUI
#   make GUI=reaction -> AmiDrop_ReAction
GUI ?= gadtools

# -MMD -MP make gcc emit a .d file per object listing the headers it read, so
# a header edit actually rebuilds. Without it, changing include/gui.h - the ABI
# contract between main.o and the frontend .o - rebuilt nothing at all.
BASE_CFLAGS := -m68000 -Os -Wall -Wextra -Wshadow -Wpointer-arith -Wframe-larger-than=1024 -DNO_INLINE_STDARG -Iinclude -MMD -MP
CFLAGS := $(BASE_CFLAGS)
LDFLAGS := -noixemul

COMMON_SOURCES := src/main.c src/server.c src/prefs.c src/util.c src/webpage.c src/qrcode.c

ifeq ($(GUI),gadtools)
  TARGET := AmiDrop
  GUI_SOURCES := src/gui.c
  GUI_LIBS :=
else ifeq ($(GUI),reaction)
  TARGET := AmiDrop_ReAction
  GUI_SOURCES := src/gui_reaction.c
  GUI_LIBS :=
  # The ReAction build ships under its own name, as it already did upstream.
  CFLAGS += -DAMIDROP_GUI_REACTION
else
  $(error Unknown GUI "$(GUI)" - use gadtools, reaction or mui)
endif

SOURCES := $(COMMON_SOURCES) $(GUI_SOURCES)

# Objects live per frontend.  Sharing one src/*.o between frontends would
# silently reuse files compiled with different flags - which is how a MUI
# binary once ended up carrying the GadTools version cookie.
OBJDIR := obj/$(GUI)
OBJECTS := $(patsubst src/%.c,$(OBJDIR)/%.o,$(SOURCES))

HOST_TEST_UTIL := tests/test_util
HOST_TEST_QR := tests/test_qr

.PHONY: all clean host-test

all: $(TARGET)

# These two must stand AFTER the first real rule: a rule placed above "all"
# would become make's default goal, and "make GUI=x" would then build one
# object file instead of the program.
#
# A flag change must rebuild, not just a source change.
$(OBJECTS): Makefile

# Per-object header dependencies generated by -MMD -MP.
-include $(OBJECTS:.o=.d)

$(TARGET): $(OBJECTS)
	$(CC) -o $@ $(OBJECTS) $(LDFLAGS) $(GUI_LIBS)

$(OBJDIR):
	mkdir -p $(OBJDIR)

$(OBJDIR)/%.o: src/%.c | $(OBJDIR)
	$(CC) $(CFLAGS) -c -o $@ $< $(LDFLAGS)

host-test: $(HOST_TEST_UTIL) $(HOST_TEST_QR)
	./$(HOST_TEST_UTIL)
	./$(HOST_TEST_QR)

$(HOST_TEST_UTIL): tests/test_util.c src/util.c include/util.h include/amidrop.h
	gcc -std=c99 -O2 -Wall -Wextra -Iinclude -o $@ tests/test_util.c src/util.c

$(HOST_TEST_QR): tests/test_qr.c src/qrcode.c include/qrcode.h include/amidrop.h
	gcc -std=c99 -O2 -Wall -Wextra -Iinclude -o $@ tests/test_qr.c src/qrcode.c

clean:
	rm -rf obj
	rm -f AmiDrop AmiDrop_ReAction AmiDrop_MUI $(HOST_TEST_UTIL) $(HOST_TEST_QR)
