#include "webpage.h"

const char amidrop_index_html[] =
"<!doctype html>\n"
"<html>\n"
"<head>\n"
"<meta charset=\"utf-8\">\n"
"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
"<title>AmiDrop</title>\n"
"<style>\n"
"*{box-sizing:border-box}\n"
"body{margin:0;background:#777;font:16px system-ui,-apple-system,Segoe UI,sans-serif;color:#111}\n"
".wrap{max-width:620px;margin:0 auto;padding:22px}\n"
".card{background:#c9c9c9;border:2px solid #eee;border-right-color:#555;border-bottom-color:#555;padding:22px;box-shadow:0 8px 24px #0005}\n"
"h1{margin:0 0 4px;font-size:30px}.sub{margin:0 0 20px;color:#333}\n"
".auth{background:#ddd;border:1px solid #777;padding:16px;margin-bottom:18px}\n"
".authrow{display:flex;gap:8px}\n"
".code{flex:1;min-width:0;border:2px inset #eee;background:#fff;padding:11px;font:700 22px monospace;letter-spacing:4px;text-align:center}\n"
".drop{background:#ddd;border:2px dashed #555;padding:30px 16px;text-align:center}\n"
"button,.pick{display:inline-block;border:2px solid #fff;border-right-color:#555;border-bottom-color:#555;background:#bbb;padding:12px 18px;font-weight:700;color:#111;cursor:pointer}\n"
"button:disabled{opacity:.5;cursor:default}input[type=file]{display:none}\n"
".files{margin:18px 0 8px;padding:0;list-style:none}.files li{padding:8px 0;border-bottom:1px solid #999;word-break:break-word}\n"
".bar{height:18px;background:#999;border:1px solid #444;margin:14px 0}.fill{height:100%;width:0;background:#333}\n"
"#status{min-height:48px;margin-top:12px}.small{font-size:13px;color:#333;margin-top:18px}.ok{font-weight:700}\n"
"[hidden]{display:none!important}\n"
"@media(max-width:520px){.wrap{padding:10px}.card{padding:16px}.drop{padding:24px 10px}.authrow{display:block}button,.pick{width:100%;margin-top:8px}.code{width:100%}}\n"
"</style>\n"
"</head>\n"
"<body>\n"
"<div class=\"wrap\"><div class=\"card\">\n"
"<h1>AmiDrop</h1><p class=\"sub\">Send files directly to your Amiga.</p>\n"
"<div id=\"auth\" class=\"auth\">\n"
"<strong>Enter the 6-digit code shown on the Amiga</strong>\n"
"<div class=\"authrow\"><input id=\"code\" class=\"code\" type=\"tel\" inputmode=\"numeric\" maxlength=\"6\" pattern=\"[0-9]*\" autocomplete=\"one-time-code\" placeholder=\"000000\"><button id=\"unlock\">Connect</button></div>\n"
"<div id=\"authStatus\" class=\"small\">On a phone you can scan the QR code in AmiDrop instead.</div>\n"
"</div>\n"
"<div id=\"panel\" hidden>\n"
"<p id=\"connected\" class=\"ok\">Connected to AmiDrop.</p>\n"
"<div id=\"drop\" class=\"drop\"><label class=\"pick\" for=\"files\">Choose files</label><input id=\"files\" type=\"file\" multiple><p>or drop files here</p></div>\n"
"<ul id=\"list\" class=\"files\"></ul><button id=\"send\" disabled>Send to Amiga</button>\n"
"<div class=\"bar\"><div id=\"fill\" class=\"fill\"></div></div><div id=\"status\">Select one or more files.</div>\n"
"</div>\n"
"<div class=\"small\">AmiDrop <span id=\"version\">1.0</span> &middot; QR/session protected &middot; maximum <span id=\"limit\">50 MB</span> per file &middot; files are sent one at a time</div>\n"
"</div></div>\n"
"<script>\n"
"const code=document.getElementById('code'),unlock=document.getElementById('unlock'),authStatus=document.getElementById('authStatus'),auth=document.getElementById('auth'),panel=document.getElementById('panel'),connected=document.getElementById('connected'),input=document.getElementById('files'),drop=document.getElementById('drop'),list=document.getElementById('list'),send=document.getElementById('send'),fill=document.getElementById('fill'),status=document.getElementById('status'),limitText=document.getElementById('limit'),versionText=document.getElementById('version');\n"
"let chosen=[],sessionCode='',sessionToken='',maxFileKB=51200;\n"
"function formatLimit(kb){if(kb<1024)return kb+' KB';if(kb<1048576)return(kb/1024)+' MB';return'1 GB'}\n"
"function loadConfig(){const x=new XMLHttpRequest();x.open('GET','/config',true);x.onload=()=>{if(x.status>=200&&x.status<300){try{const c=JSON.parse(x.responseText);if(c.maxFileKB>=512){maxFileKB=c.maxFileKB;limitText.textContent=formatLimit(maxFileKB)}if(c.version)versionText.textContent=c.version}catch(e){}}};x.send(null)}\n"
"code.addEventListener('input',()=>{code.value=code.value.replace(/[^0-9]/g,'').slice(0,6)});\n"
"function applyAuth(x){if(sessionToken)x.setRequestHeader('X-AmiDrop-Token',sessionToken);else if(sessionCode)x.setRequestHeader('X-AmiDrop-Code',sessionCode)}\n"
"function showConnected(viaQr){auth.hidden=true;panel.hidden=false;connected.textContent=viaQr?'Connected to AmiDrop via QR code.':'Connected to AmiDrop.';status.textContent='Select one or more files.'}\n"
"function authError(x){if(x.status===429)return'Too many wrong attempts. Wait 30 seconds and try again.';return'Wrong or expired code. Check the AmiDrop window and try again.'}\n"
"function authorizeCode(){const c=code.value;if(!/^\\d{6}$/.test(c)){authStatus.textContent='Please enter all 6 digits.';code.focus();return}unlock.disabled=true;authStatus.textContent='Connecting...';const x=new XMLHttpRequest();x.open('POST','/auth',true);x.setRequestHeader('X-AmiDrop-Code',c);x.onload=()=>{unlock.disabled=false;if(x.status>=200&&x.status<300){sessionCode=c;sessionToken='';showConnected(false)}else{sessionCode='';authStatus.textContent=authError(x);code.select()}};x.onerror=()=>{unlock.disabled=false;authStatus.textContent='Could not reach AmiDrop.'};x.send(null)}\n"
"function authorizeToken(t){sessionToken=t;sessionCode='';unlock.disabled=true;code.disabled=true;authStatus.textContent='Authorizing QR session...';const x=new XMLHttpRequest();x.open('POST','/auth',true);x.setRequestHeader('X-AmiDrop-Token',t);x.onload=()=>{if(x.status>=200&&x.status<300){try{history.replaceState(null,'',location.pathname)}catch(e){}showConnected(true)}else{sessionToken='';unlock.disabled=false;code.disabled=false;authStatus.textContent=x.status===429?'Access is temporarily locked. Wait 30 seconds, then scan the current QR code again.':'This QR code has expired. Scan the current QR code shown by AmiDrop.';code.focus()}};x.onerror=()=>{sessionToken='';unlock.disabled=false;code.disabled=false;authStatus.textContent='Could not reach AmiDrop.';code.focus()};x.send(null)}\n"
"unlock.onclick=authorizeCode;code.addEventListener('keydown',e=>{if(e.key==='Enter')authorizeCode()});\n"
"function fmt(n){if(n<1024)return n+' B';if(n<1048576)return(n/1024).toFixed(1)+' KB';return(n/1048576).toFixed(1)+' MB'}\n"
"function setFiles(fs){chosen=Array.from(fs);list.innerHTML='';chosen.forEach(f=>{const li=document.createElement('li');li.textContent=f.name+' — '+fmt(f.size);list.appendChild(li)});send.disabled=!chosen.length;status.textContent=chosen.length?chosen.length+' file(s) ready.':'Select one or more files.';fill.style.width='0%'}\n"
"input.onchange=()=>setFiles(input.files);['dragenter','dragover'].forEach(e=>drop.addEventListener(e,x=>{x.preventDefault();drop.style.background='#eee'}));['dragleave','drop'].forEach(e=>drop.addEventListener(e,x=>{x.preventDefault();drop.style.background='#ddd'}));drop.addEventListener('drop',e=>setFiles(e.dataTransfer.files));\n"
"function uploadOne(file,index){return new Promise((resolve,reject)=>{if(file.size>maxFileKB*1024){reject(new Error(file.name+': larger than the AmiDrop limit ('+formatLimit(maxFileKB)+')'));return}const x=new XMLHttpRequest();x.open('POST','/upload',true);x.setRequestHeader('Content-Type','application/octet-stream');applyAuth(x);x.setRequestHeader('X-AmiDrop-Filename',encodeURIComponent(file.name));x.upload.onprogress=e=>{if(e.lengthComputable){const p=Math.round(e.loaded/e.total*100);fill.style.width=p+'%';status.textContent='Sending '+(index+1)+'/'+chosen.length+': '+file.name+' — '+p+'%'}};x.onload=()=>{if(x.status>=200&&x.status<300)resolve();else if(x.status===403)reject(new Error('session expired; reconnect or scan the current QR code'));else if(x.status===429)reject(new Error('access temporarily locked; wait 30 seconds'));else reject(new Error(file.name+': '+(x.responseText||('HTTP '+x.status))))};x.onerror=()=>reject(new Error(file.name+': connection interrupted'));x.onabort=()=>reject(new Error(file.name+': transfer aborted'));x.send(file)})}\n"
"send.onclick=async()=>{if(!sessionCode&&!sessionToken)return;send.disabled=true;input.disabled=true;try{for(let i=0;i<chosen.length;i++){fill.style.width='0%';await uploadOne(chosen[i],i)}fill.style.width='100%';status.textContent='Done. '+chosen.length+' file(s) received by the Amiga.'}catch(e){fill.style.width='0%';status.textContent='Error: '+e.message}finally{send.disabled=!chosen.length;input.disabled=false}};\n"
"loadConfig();const qrToken=new URLSearchParams(location.search).get('t');if(qrToken&&/^[A-HJ-NP-Z2-9]{20}$/.test(qrToken))authorizeToken(qrToken);else code.focus();\n"
"</script>\n"
"</body></html>\n";
